-- 코드를 입력하세요
SELECT c.CAR_ID, c.CAR_TYPE, round(DAILY_FEE * 30 * (100 - discount_rate) / 100, 0) as fee
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
)
AND DURATION_TYPE LIKE '30일%'
HAVING fee BETWEEN 500000 AND 1999999 
AND c.car_type IN ('세단', 'SUV')
ORDER BY fee DESC, car_type, car_id DESC;
