SET @HOUR = -1; # 초기값 
SELECT (@HOUR := @HOUR +1) AS HOUR, #1씩 더함, := 주의!!!
    (SELECT COUNT(HOUR(DATETIME)) 
    FROM ANIMAL_OUTS 
    WHERE HOUR(DATETIME)=@HOUR) AS COUNT 
    FROM ANIMAL_OUTS
WHERE @HOUR < 23;